namespace UnityMVC.Protocol
{
/// <summary>
/// Web
/// </summary>
    public enum WebReturnCode
   {
		OK, 
       URL_ERROR = 404,      
       #region common 
	    NORESULT,
	    SYSTEM_ERROR,
	    ERROR_UNAUTHOR_OR_AUTHOR_TIMEOUT,
	    SERVICE_TIMEOUT,
	    ERROR,
       PLAYER_CANT_LEVELUP=1,  //
       PLAYER_SKILL_CANT_LEVELUP=2,  //
       PLAYER_CANT_WAKEUP=3,  //
       DB_ERROR=8,  //
       ROLE_NOT_FOUND=9,  //
       ACCOUNT_NOT_FOUND=10,  //
       ACCOUNT_PASSWORD_NOT_MATCH=11,  //
       ACCOUNT_ALREADY_EXISTS=12,  //
       ROLE_ALREADY_EXISTS=13,  //
		SENSITIVE_WORDS=16,  //

       NOT_ENOUGH_GOLD=21,  //
       NOT_ENOUGH_DIAMOND=22,  //
       NOT_ENOUGH_POWER=23,  //
       NOT_ENOUGH_ENERGY=24,  //
       NOT_ENOUGH_XT=25,  //
       NOT_ENOUGH_XH=26,  //
       NOT_ENOUGH_DH=27,  //
       NOT_ENOUGH_XSYP=28,  //
       NOT_ENOUGH_XHGX=29,  //
       NOT_ENOUGH_XJ=30,  //
       NOT_ENOUGH_CWSL=31,  //
       LEVEL_LOCKED=101,  //
       LEVEL_NOT_FOUND=102,  //
       LEVEL_NOT_PASSED=103,  //
       LEVEL_PLAY_COUNT_REACH_LIMIT=104,  //
       LEVEL_RESET_COUNT_REACH_LIMIT=105,  //
       EQUIP_NOT_FOUND=201,  //
       EQUIP_QIANGHUA_REACH_LIMIT=202,  //
       NOT_ENOUGH_EQUIP_JINGLIAN_ITEM=203,  //
       NOT_ENOUGH_EQUIP_HECHENG_ITEM=204,  //
       ONE_CLICK_QIGNAHUA_FAILED=205,  //
       ONE_CLICK_HUANZHUANG_FAILED=206,  //
       EQUIP_JINGLIAN_REACH_LIMIT=207,  //
       PARTNER_NOT_FOUND=301,  //
       NOT_ENOUGH_FABAO_FRAG=302,  //
       NOT_ENOUGH_EXP_BOTTLE_FOR_PARTNER_UPGRADE=303,  //
       NOT_ENOUGH_EXP_BOTTLE_FOR_PARTNER_JINJIE=304,  //
       NOT_ENOUGH_EXP_BOTTLE_FOR_PARTNER_JUEXING=305,  //
       SKILL_UPGRADE_CONSUMPTION_CONFIG_ERROR=307,  //
       NOT_ENOUGH_SKILL_UPGRADE_CONSUMPTION=308,  //
       SKILL_ORDER_ERROR=309,  //
       PARTNER_JINJIE_REACH_LIMIT=310,  //
       NOT_ENOUGH_PARTNER_COUNT_FOR_JINJIE=311,  //
       SKILL_UPGRADE_REACH_LIMIT=312,  //
	   ALL_EQUIPS_MAXQIANGHUALEVEL=318,//
	   XIANSHI_HUODONG_FINISH=319,//
	   XIANSHI_TASK_FINISH=320,//
	   NO_MAKE_EQUIP=323,//
       FABAO_NOT_FOUND=501,  //
       FABAO_JINGLIAN_LEVEL_REACH_LIMIT=502,  //
       NOT_ENOUGH_FABAO_JINGLIAN_ITEM=503,  //
       FABAO_FRAG_NOT_FOUND=504,  //
       FABAO_CANT_BE_JINGLIAN=505,  //
       FABAO_CANT_BE_QIANGHUA=506,  //
       CANT_FIND_TARGET_FOR_DFQD=507,  //
       FABAO_QIANGHUA_LEVEL_REACH_LIMIT=508,  //
       NOT_ENOUGH_EXP_FOR_FABAO_QIANGHUA=509,  //
	   NOT_ENOUGH_ADDFABAO=510,//
	   SELECT_MAXFABAO=511,//
	   NOT_ENOUGH_JUXIANLING=512,// 
       ROLE_NOT_FOUND_FOR_ADMIRE=601,  //
       BATTLE_TYPE_ERROR=602,  //
       CANT_FIND_TARGET_FOR_JJC=603,  //
       NOT_ENOUGH_ADMIRE_COUNT=604,  //
       NOT_ENOUGH_PLAY_COUNT_FOR_JJC=605,  //
       LIANHUA_ERROR=701,  //
       DYT_ERROR=801,  //
       DYT_SWEEP_ERROR_TIME_NOT_MATCH=802,  //
       NOT_ENOUGH_PLAY_COUNT_FOR_DYT=803,  //
       NOT_ENOUGH_RESET_COUNT_FOR_DYT=804,  //
       ROUND_COUNT_NOT_MATCH=805,  //
       NOT_IN_SWEEPING=806,  //
       ALREADY_IN_SWEEPING=807,  //
       ALREADY_GO_TO_THE_TOP=808,  //
       WHAT=809,  //22222
       VIP_NOT_FOUND=901,  //Vip
       LIANJING_REACH_LIMIT=902,  //
       NOT_ENOUGH_LIANJING_DIAMOND=903,  //
       ALREADY_SIGN=904,  //
	   NOT_ENOUGH_JIFEN=905,// 
       ITEM_NOT_FOUND=1001,  //
       NOT_ENOUGH_ITEM=1002,  //
       MAIL_NOT_FOUND=1101,  //
       MAIL_ALREADY_READ=1102,  //
       NOT_ENOUGH_STORE_REFRESH_COUNT=1201,  //
       NOT_ENOUGH_STORE_REFRESH_STONE=1202,  //
       NO_GOODS=1203,  //
       NOT_ENOUGH_XIANGOU_COUNT=1204,  //
       STORE_NOT_FOUND=1205,  //
       GOOD_NOT_FOUND=1206,  //
       OPEN_REQIREMENT_NOT_MATCH=1207,  //
       XIANGOU_REQUIREMENT_NOT_MATCH=1208,  //
       GOOD_NOT_IN_STORE=1209,  //
       STORE_CANT_OPEN=1210,  //
       PARTNER_LEVEL_NOT_MATCH=1300,  //
       PLAYER_LEVEL_NOT_MATCH=1301,  //
       VIP_LEVEL_NOT_MATCH=1302,  //vip
       DYT_RECORD_NOT_MATCH=1303,  //
       GONGHUI_LEVEL_NOT_MATCH=1304,  //
     RTN_END = 1000,
   #endregion
   }
}
