using UnityEngine;
using System.Collections;

/// <summary>
/// NOTE: fly spell or buff spell is generated by programming, dont attach this script!
/// </summary>
public class DestroySpellTimed : SpellMono {

    private void Awake()
    {
        Destroy(gameObject, getMaxParticleLife());
    }


}
